version: '3.8'

services:
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cvortexdb
            MYSQL_USER: cvortex
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - "9000:80"
        restart: always
          # volumes:
        # - .:/usr/local/etc/php
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 202M

volumes:
    db_data: {}
